"""add default field on Recipe

Revision ID: 8df81be15b6b
Revises: 48afa8d7c5cf
Create Date: 2026-02-09 08:58:41.028615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8df81be15b6b'
down_revision: Union[str, Sequence[str], None] = '48afa8d7c5cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Menggunakan batch_alter_table untuk mendukung SQLite
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.alter_column('grind_size',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
        batch_op.alter_column('bean_name',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
        batch_op.alter_column('bean_process',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
        batch_op.alter_column('bean_roast_level',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
        batch_op.alter_column('bean_roast_date',
                   existing_type=sa.VARCHAR(),
                   nullable=False)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipe', 'bean_roast_date',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('recipe', 'bean_roast_level',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('recipe', 'bean_process',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('recipe', 'bean_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('recipe', 'grind_size',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
