"""set data type str established_year Roastery

Revision ID: cdfc0dc50257
Revises: 8df81be15b6b
Create Date: 2026-02-09 09:47:13.200590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cdfc0dc50257'
down_revision: Union[str, Sequence[str], None] = '8df81be15b6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Batch pertama untuk tabel 'recipe'
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.alter_column('bean_name',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
        batch_op.alter_column('bean_process',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
        batch_op.alter_column('bean_roast_level',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
        batch_op.alter_column('bean_roast_date',
                   existing_type=sa.VARCHAR(),
                   nullable=True)

    # Batch kedua untuk tabel 'roastery'
    with op.batch_alter_table('roastery', schema=None) as batch_op:
        batch_op.alter_column('established_year',
                   existing_type=sa.INTEGER(),
                   type_=sa.String(), # Pastikan sa.String() tersedia atau gunakan type_ langsung
                   existing_nullable=True)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roastery', 'established_year',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('recipe', 'bean_roast_date',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('recipe', 'bean_roast_level',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('recipe', 'bean_process',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('recipe', 'bean_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
