"""init SQLModel Migrations

Revision ID: f1ed49946365
Revises: 
Create Date: 2026-02-09 08:20:23.346412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f1ed49946365'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ratio', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grind_size', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('water_temp', sa.Float(), nullable=False),
    sa.Column('bean_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bean_process', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bean_roast_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bean_roast_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe')
    # ### end Alembic commands ###
